"""Export the training data order HF Trainer used for seeds 1001 / 1002 (CPU only).

Builds a real transformers Trainer (same versions as training: transformers
4.45.2, accelerate 0.34.2, torch 2.4.0) with the training batch settings and a
dummy model over a 20000-row index dataset, pulls get_train_dataloader(), and
records which row index lands at each position. Also checks that the order equals
torch.randperm(20000, generator seeded with seed) so the null orders below can be
generated by randperm alone.

    CUDA_VISIBLE_DEVICES= python export_order.py <out.npz>
"""
import os
import sys
import tempfile

os.environ["CUDA_VISIBLE_DEVICES"] = ""
import numpy as np
import torch
from datasets import Dataset
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments

N = 20000
N_NULL = 1000


class Dummy(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.w = torch.nn.Parameter(torch.zeros(1))

    def forward(self, idx=None, **kw):
        return {"loss": self.w.sum()}


def collate(b):
    return {"idx": torch.tensor([x["idx"] for x in b])}


def trainer_order(seed):
    args = Seq2SeqTrainingArguments(
        output_dir=tempfile.mkdtemp(), per_device_train_batch_size=8,
        gradient_accumulation_steps=2, num_train_epochs=1.0, seed=seed,
        report_to="none", use_cpu=True, remove_unused_columns=False)
    ds = Dataset.from_dict({"idx": list(range(N))})
    tr = Seq2SeqTrainer(model=Dummy(), args=args, train_dataset=ds,
                        data_collator=collate)
    dl = tr.get_train_dataloader()
    order = torch.cat([b["idx"] for b in dl]).numpy()
    assert sorted(order.tolist()) == list(range(N))
    return order


def randperm(seed):
    g = torch.Generator()
    g.manual_seed(seed)
    return torch.randperm(N, generator=g).numpy()


if __name__ == "__main__":
    out = {}
    for s in (1001, 1002):
        o = trainer_order(s)
        same = bool((o == randperm(s)).all())
        print(f"seed {s}: trainer order == randperm: {same}; first 8 {o[:8].tolist()}")
        out[f"order_{s}"] = o
        out[f"same_{s}"] = np.array(same)
    out["null"] = np.stack([randperm(s) for s in range(N_NULL)])
    np.savez_compressed(sys.argv[1], **out)
    print("wrote", sys.argv[1])
