bf16: false
cutoff_len: 768
dataset: arm_p_0_71
dataset_dir: /root/amic-q3/data/lf
disable_gradient_checkpointing: true
do_train: true
finetuning_type: lora
flash_attn: disabled
fp16: true
freeze_language_model: false
freeze_multi_modal_projector: true
freeze_vision_tower: true
gradient_accumulation_steps: 4
image_max_pixels: 589824
image_min_pixels: 589824
learning_rate: 0.0001
logging_steps: 20
lora_alpha: 32
lora_dropout: 0.05
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: /data/models/Qwen3-VL-8B-Instruct
num_train_epochs: 1.0
output_dir: /root/amic-q3/runs/arms/P-0.71
overwrite_output_dir: false
per_device_train_batch_size: 4
plot_loss: false
preprocessing_num_workers: 8
report_to: none
save_steps: 79
save_strategy: steps
seed: 1001
stage: sft
template: qwen3_vl_nothink
warmup_ratio: 0.03
